[package]
edition = "2024"
rust-version = "1.93.0"
name = "powercurve"
version = "0.4.0"
authors = ["John Crenshaw"]
license = "GPL-3.0-only"
description = "Lightweight desktop power management daemon with configurable fan curves"
repository = "https://github.com/crenshawdev/powercurve"

[package.metadata.deb]
license-file = "LICENSE"
depends = "dbus"
provides = "power-profiles-daemon"
conflicts = "power-profiles-daemon"
maintainer-scripts = "debian/"
assets = [
    [
    "target/release/powercurve",
    "usr/bin/",
    "755",
],
    [
    "data/com.vintagetechie.PowerCurve.conf",
    "usr/share/dbus-1/system.d/",
    "644",
],
    [
    "data/com.vintagetechie.PowerCurve.xml",
    "usr/share/dbus-1/interfaces/",
    "644",
],
    [
    "data/com.vintagetechie.PowerCurve.service",
    "usr/lib/systemd/system/",
    "644",
],
    [
    "data/powercurve-monitor.service",
    "usr/lib/systemd/user/",
    "644",
],
    [
    "data/powercurve-watcher.service",
    "usr/lib/systemd/user/",
    "644",
],
    [
    "man/powercurve.1",
    "usr/share/man/man1/",
    "644",
],
    [
    "examples/fan-simple.toml",
    "usr/share/doc/powercurve/examples/",
    "644",
],
    [
    "examples/fan-desktop.toml",
    "usr/share/doc/powercurve/examples/",
    "644",
],
    [
    "examples/fan-profiles.toml",
    "usr/share/doc/powercurve/examples/",
    "644",
],
    [
    "examples/watcher.toml",
    "usr/share/doc/powercurve/examples/",
    "644",
],
]

[dependencies]
anyhow = "1"
concat-in-place = "1"
dirs = "6"
fern = "0.7"
futures-lite = "2"
glob = "0.3"
intel-pstate = "1"
libc = "0.2"
log = "0.4"
regex = "1"
sd-notify = "0.5.0"
sysfs-class = "0.1.3"
thiserror = "2"
toml = "1"
zvariant = "3"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.powercurve-zbus]
path = "zbus"

[dependencies.serde]
workspace = true

[dependencies.tokio]
version = "1"
features = [
    "macros",
    "rt",
    "time",
    "signal",
]

[dependencies.zbus]
version = "3"
features = ["tokio"]
default-features = false

[dev-dependencies]
env_logger = "0.11"

[lints]
workspace = true

[workspace]
members = [
    "zbus",
]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"
